### ISSUE TITLE
pull down menu doesn't work in local head

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#154] opened 2018-10-11 19:01 UTC
Pull down menus don't pull down when running a local head. For instance, clicking the down arrow to change the current program from the Auto tab on the Control page does not pull down the list of programs that are available in the controller.

**Comment by jcoffland** [comment] 2018-10-16 22:45
Works for me.  Are you sure you're running the latest firmware?  This was a bug fixed in a previous version.

**Comment by jcoffland** [comment] 2018-10-16 23:32
This was caused by running an outdated base image.

**Closed by jcoffland** 2018-10-16 23:32 UTC
Labels: invalid
